title: Code for Kobe
description: ITで神戸をもっと素敵な街にするため活動するコミュニティです。
google_analytics: UA-93922008-1
show_downloads: false
theme: jekyll-theme-minimal

markdown: kramdown
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
